name: Create Release ZIP

on:
  push:
    tags:
      - 'v*.*.*'  # 监听符合 vX.X.X 格式的标签

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get repository name
      id: repo
      run: echo "name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

    - name: Get version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Create ZIP file
      run: |
        FILENAME="${name}-${version}.zip"
        echo "Creating ZIP file: $FILENAME"
        zip -r "$FILENAME" .

    - name: Upload release asset
      uses: actions/upload-artifact@latest
      with:
        name: ${{ env.name }}-${{ env.version }}
        path: ${{ env.name }}-${{ env.version }}.zip
